export const spotIds = {
  'Saltstein': {msw: {id: 556}, yr: {id: '1-2275034', name: 'Nevlungstranda'}},
  'Esso': {msw: {id: 556, name: 'Saltstein'}, yr: {id: '5-17280', name: 'Gullholmen'}},
  'Øya': {msw: {id: 556, name: 'Saltstein'}, yr: {id: '1-33424', name: 'Sandø'}},
  'Ins and outs': {msw: {id: 556, name: 'Saltstein'}, yr: {id: '1-2275034', name: 'Nevlungstranda'}},
  'Elvemunningen': {msw: {id: 556, name: 'Saltstein'}, yr: {id: '1-2275034', name: 'Nevlungstranda'}},
  'Skallevold': {msw: {id: 556, name: 'Saltstein'}, yr: {id: '5-17280', name: 'Gullholmen'}},
  'Unstad, right': {msw: {id: 674, name: 'Unstad beach'}},
  'Unstad, left': {msw: {id: 674, name: 'Unstad beach'}},
  'Unstad, beach': {msw: {id: 674, name: 'Unstad beach'}},
  'Ervik': {msw: {id: 1893}, yr: {id: '1-2659002'}},
  'Hoddevika': {msw: {id: 552}, yr: {id: '1-2297215'}},
  'Alnes Fyr': {msw: {id: 4660}, yr: {id: '1-181785'}},
  'Flø': {msw: {id: 4660, name: 'Alnes Fyr'}, yr: {id: ''}},
  'Svinestien': {msw: {id: 1884, name: 'Pigsty-Piggy'}, yr: {id: '1-15649'}},
  'Reve Havn': {msw: {id: 1885}, yr: {id: '1-15649'}},
  'Kvassheim': {msw: {id: 1892}, yr: {id: '1-8454'}},
  'Sele': {msw: {id: 554}, yr: {id: '1-15564'}},
  'Bore': {msw: {id: 1886}, yr: {id: '1-15564'}},
  'Trestles, uppers': {msw: {id: 291, name: 'Trestles'}},
  'Carlsbad': {msw: {id: 292}},
  'Cotton': {msw: {id: 291, name: 'Trestles'}},
  'Ocean Beach': {msw: {id: 4212}},
  'Blacks Beach': {msw: {id: 8146}},
  'Georges´s': {msw: {id: 4663, name: 'Cardiff-Reef'}},
  'Seaside Reef': {msw: {id: 4663, name: 'Cardiff-Reef'}},
  'Ponto Jetties': {msw: {id: 1149, name: 'Ponto'}},
  'Cardiff Reef': {msw: {id: 4663}},
  'Torrey Pines State Beach S.': {msw: {id: 295, name: 'Torrey-Pines-Blacks-Beach'}},
  'Sunset Cliffs': {msw: {id: 4211}},
  'Fletcher Cove': {msw: {id: 294, name: 'Solana-Beach'}},
  'Sao Pedro': {msw: {id: 912, name: 'Carcavelos'}},
  'Carcavelos': {msw: {id: 912}},
  'Matador': {msw: {id: 4343, name: 'Ribeira-dIlhas'}},
  'Ribeira': {msw: {id: 4343, name: 'Ribeira-dIlhas'}},
  'Baleal': {msw: {id: 6707}},
  'Supertubos': {msw: {id: 196}},
  'Lagide': {msw: {id: 195}},
  'Praia da Luz': {msw: {id: 4325}},
  'Arrifana': {msw: {id: 836}},
  'Beliche': {msw: {id: 4323}},
  'Praia da Ingrina': {msw: {id: 4324, name: 'Zavial'}},
  'Praia das Furnas': {msw: {id: 5831}},
  'Praia do Barranco': {msw: {id: 5830}},
  'Zavial': {msw: {id: 4324}},
  'Praia do Martinhal': {msw: {id: 5828}},
  'Sagres (south)': {msw: {id: 1098, name: 'Sagres-South'}},
  'El Charco': {msw: {id: 1853}},
  'La Izquierda': {msw: {id: 1853, name: 'El Charco'}},
  'El Arenal': {msw: {id: 1853, name: 'El Charco'}},
  'Are Goling': {msw: {id: 4170, name: 'Air-Guling'}},
  'Senggigi': {msw: {id: 4130}},
  'Outside Grupuk': {msw: {id: 4129}},
  'Outside Grupuk Left': {msw: {id: 4129, name: 'Outside Grupuk'}},
  'Tanjung': {msw: {id: 4129, name: 'Outside Grupuk'}},
  'Don-Don': {msw: {id: 4123}},
  'Inside Grupuk': {msw: {id: 4126}},
  'Coconut': {msw: {id: 4589 , name: 'Rams Midigama'}},
  'Fishermans Reef': {msw: {id: 4589 , name: 'Rams Midigama'}}
}



